TK1PPW/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('home/', include('homepage.urls')),
    path('jadwalmu/', include('schedule.urls')),
    path('todolist/', include('todo.urls')),
    path('nilaimu/', include('nilai.urls')),
    path('catatan/', include('notes.urls')),
]

nilai/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'nilai'

urlpatterns = [
    path('input_nilai', views.index, name="index"),
    path('daftar_nilai',views.daftar_nilai, name="daftar_nilai"),
    path('hapus/<hapus_id>[0-9]', views.hapus, name="hapus")
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'todo'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('tambah/', views.tambahTodo, name="tambah"),
    path('<int:pk>/delete', views.delete_todo, name='delete'),
    
]

nilai/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date
# Create your models here.

class rata_nilai(models.Model):
    nama_nilai = models.CharField(max_length=100)
    isian_nilai = models.PositiveIntegerField(null=True)
    # def __str__(self):
    #     return self.rata_nilai

nilai/forms.py
from .models import rata_nilai
from django import forms

class Input_Form(forms.ModelForm):
    class Meta:
        model = rata_nilai
        fields = ['nama_nilai',
        'isian_nilai',]

    isian_nilai = forms.IntegerField(label='', required=True, min_value=0, widget=forms.NumberInput(attrs={'class':'form-control','id':'isian_nilai'}))
    nama_nilai = forms.CharField(label='', required=True, max_length=100, widget=forms.TextInput(attrs={'class':'form-control','id':'nama_nilai', 'placeholder':'contoh : UTS, UAS, Latihan'}))

nilai/views.py
from django.shortcuts import render, redirect
from .forms import Input_Form
from django.http import HttpResponseRedirect, HttpResponse
from .models import rata_nilai

# Create your views here.
respons = {}
def index(request):
    form = Input_Form(request.POST or None)
    if (form.is_valid and request.method == 'POST'):
        form.save()
        return redirect('/nilaimu/daftar_nilai')
    respons['input_form'] = form
    return render(request, 'nilai/input_nilai.html', respons)

def daftar_nilai(request):
    tipe_nilai = rata_nilai.objects.all()
    respons['tipe_nilai'] = tipe_nilai
    return render(request,'nilai/daftar_nilai.html', respons)

def hapus(request, hapus_id):
    rata_nilai.objects.filter(id=hapus_id).delete()
    return redirect('/nilaimu/daftar_nilai')

nilai/templates/nilai/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Nilai Mu</title>
    <link rel="stylesheet" href="../../static/todo/style.css" type="text/css" media="screen">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" 
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" 
    crossorigin="anonymous">
</head>

<body>
    {% block content %}
    {% endblock %}

</body>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</html>

nilai/templates/nilai/daftar_nilai.html
{% extends 'homepage/base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h1>Daftar nilai kamu</h1>
    <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">No</th>
            <th scope="col">Kategori</th>
            <th scope="col">Nilai</th>
          </tr>
        </thead>
        <tbody>
        {% if tipe_nilai %} {% for tipe in tipe_nilai %}
          <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td>{{ tipe.nama_nilai }}</td>
            <td>{{ tipe.isian_nilai }}</td>
            <td><a href="{% url 'nilai:hapus' tipe.id %}" id="hapus">
              <button type="button" class="btn btn-danger">Hapus</button>
          </a>
        </td>
          </tr>
        {% endfor %}
        {% endif %}
        </tbody>
      </table>
      <a href="/nilaimu/input_nilai" id="input_nilai">
        <button type="button" class="btn btn-success">Tambah</button>
    </a>
</div>

{% endblock %}

nilai/templates/nilai/input_nilai.html
{% extends 'homepage/base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h1>Ayo list nilai kamu</h1>
    <form class="input_teks" action="" method="POST">
        {% csrf_token %}
        <label for="p_latihan">Kategori nilai :</label> {{input_form.nama_nilai}}
        <br>
        <label for="p_uts">Nilai :</label> {{input_form.isian_nilai}}
        <br>
        <input type="submit" name="Masukkan" class="btn btn-primary button-submit" value="Simpan">
        <h5>Jika kamu sudah memiliki list nilai sebelumnya, 
            <a href="/nilaimu/daftar_nilai" id="daftar_nilai">
                <button type="button" class="btn btn-link"> klik disini</button>
            </a>
        </h5>
    </form>
</div>
{% endblock %}