TK1PPW/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('home/', include('homepage.urls')),
    path('jadwalmu/', include('schedule.urls')),
    path('todolist/', include('todo.urls')),
    path('nilaimu/', include('nilai.urls')),
    path('catatan/', include('notes.urls')),
]

homepage/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'homepage'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    
]

nilai/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'nilai'

urlpatterns = [
    path('input_nilai', views.index, name="index"),
    path('daftar_nilai',views.daftar_nilai, name="daftar_nilai"),
    path('hapus/<hapus_id>[0-9]', views.hapus, name="hapus")
]

notes/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'notes'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    
]

schedule/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'schedule'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.add, name="index"),
    path('<str:nama_matkul>', views.detail_jadwal),
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<str:nama_matkul>', views.destroy),  
    
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'todo'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('tambah/', views.tambahTodo, name="tambah"),
    path('<int:pk>/delete', views.delete_todo, name='delete'),
    
]

todo/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    activity = models.CharField(max_length=50)

    def __str__(self):
        return self.activity

todo/forms.py
from django import forms
from .models import Todo

class TodoForm(forms.ModelForm):
    activity = forms.CharField(label='')
    activity.widget.attrs.update({'class':'todo-form', 'required':'required'})
    class Meta:
        model = Todo
        fields = ('activity',)

todo/views.py
from django.shortcuts import render,redirect
from .models import Todo
from .forms import TodoForm
# Create your views here.
def index(request):
    activity = Todo.objects.all()
    if request.method == 'POST':
        formtambah= TodoForm(request.POST)
        if formtambah.is_valid():
            formtambah.save()
            return redirect('todo:index')
    else:
        formtambah= TodoForm()
    return render(request,'todo/todo.html',{
        'activity' : activity,
        'formtambah':formtambah
    })

def tambahTodo(request):
    return render(request, "todo/todo.html")

def delete_todo(request, pk):
    activity = Todo.objects.get(pk=pk)
    activity.delete()
    return redirect('todo:index')

todo/templates/todo/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>To Do List</title>
    <link href='https://fonts.googleapis.com/css?family=ABeeZee' rel='stylesheet'>
    <link href="../../static/todo/style.css" rel="stylesheet"  type="text/css" media="screen">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" 
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" 
    crossorigin="anonymous">
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
</head>

<body>
    <div class="sidenav">
        <div class="halo">
            <h1 style="font-size: 18px;">Halo</h1>
        </div>
        <a href="{% url 'homepage:index' %}">Home</a>
        <a href="{% url 'schedule:index' %}">Jadwal</a>
        <a href="{% url 'todo:index' %}"><u>To Do List</u></a>
        <a href="{% url 'nilai:index' %}">Nilai</a>
        <a href="{% url 'notes:index' %}">Notes</a>
        <button type="button" class="btn btn-outline-dark">Log out</button>
    </div>
    {% block content %}
    {% endblock %}

</body>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</html>

todo/templates/todo/todo.html
{% extends 'todo/base.html' %}
{% load static %}

{% block content %}
<body>

    <div class="container">
        <h1>To-Do List</h1>
        <div class="row">
            <div class="col-sm col-form">
                <div class = "container-sm container-form">
                    <div class="row row-button">
                        <div class="w-100"></div>
                        <div class="col-sm col-form">
                            <form action='' method="post">
                                {% csrf_token %}
                                {{ formtambah.as_p }}
                                <div class="col-sm col-tambah">
                                    <a href ="{% url 'todo:tambah' %}"><button type="submit" class="btn btn-success tambah-btn">tambah</button></a>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>
            </div>
            
            <div class="col-sm col-todo">
                <div class = "container-sm container-todo">
                    {% if activity %}
                        {% for activities in activity %}
                        <table class="table table-borderless">
                            <tr>
                                <td>
                                    <ul>
                                        <li>
                                            {{activities.activity}}
                                        </li>
                                    </ul>
                                </td>
                                <td>
                                    <a href="{% url 'todo:delete' activities.pk %}"><button class="btn btn-success hapus-btn" type="submit"><i class='fa fa-chevron-down' style='font-size:18px'></i></button></a>
                                </td>
                            </tr>
                        </table>
                        
                        {% endfor %}
                    {% else %}
                        <h3>Tambahkan Todo list mu!</h3>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %}
</html>