TK1PPW/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('home/', include('homepage.urls')),
    path('jadwalmu/', include('schedule.urls')),
    path('todolist/', include('todo.urls')),
    path('nilaimu/', include('nilai.urls')),
    path('catatan/', include('notes.urls')),
]

homepage/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'homepage'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    
]

nilai/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'nilai'

urlpatterns = [
    path('input_nilai', views.index, name="index"),
    path('daftar_nilai',views.daftar_nilai, name="daftar_nilai"),
    path('hapus/<hapus_id>[0-9]', views.hapus, name="hapus")
]

notes/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'notes'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    
]

schedule/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'schedule'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.add, name="index"),
    path('<str:nama_matkul>', views.detail_jadwal),
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<str:nama_matkul>', views.destroy),  
    
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'todo'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('tambah/', views.tambahTodo, name="tambah"),
    path('<int:pk>/delete', views.delete_todo, name='delete'),
    
]

schedule/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Jadwal(models.Model):
    jadwalpelajaran = models.CharField(max_length=100)
    deskripsi = models.CharField(max_length=200)
    datetime = models.DateTimeField(default=timezone.now())
    lokasi = models.CharField(max_length=64)
    
    def __str__(self):
        return self.jadwalpelajaran

schedule/forms.py
from django import forms
from .models import Jadwal

years = [x for x in range(2020, 2050)]

class JadwalForms(forms.ModelForm):
    jadwalpelajaran = forms.CharField(widget=forms.TextInput(attrs={
        "label" : "Nama Pelajaran",
        "class" : "form-control",
        "required" : True,
        "placeholder" : "Schedule Name",
        
    }))

    deskripsi = forms.CharField(widget=forms.TextInput(attrs={
        "class" : "form-control",
        "required" : False,
        "placeholder" : "Deskripsi",
    }))

    datetime = forms.DateField(
        widget = forms.SelectDateWidget(years = years, attrs = {'class' : 'form-control-sm'})
    )


    lokasi = forms.CharField(widget=forms.TextInput(attrs={
        "class" : "form-control",
        "required" : True,
        "placeholder" : "zoom",
    }))

    class Meta:
        model = Jadwal
        fields = ['jadwalpelajaran', 'deskripsi', 'datetime', 'lokasi']

schedule/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Jadwal
from .forms import JadwalForms




# Create your views here.
# def index(request):
#     return render(request,'schedule/schedule.html')

def add(request):  
    data = Jadwal.objects.all() 
    form = JadwalForms()
    if request.method == "POST":  
        form = JadwalForms(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/jadwalmu')  
            except:  
                pass  
    else:  
        form = JadwalForms()

    response = {
        'form': form,
        'data' : data,
        
    }  
    #print(response)
    print("masuk")
    return render(request,'schedule/schedule.html', response)  

def detail_jadwal(request, nama_matkul):
    data = Jadwal.objects.filter(jadwalpelajaran=nama_matkul)
    response = {
        'data': data,
    }
    return render(request, 'schedule/listJadwal.html', response)



def destroy(request, nama_matkul):  
    data = Jadwal.objects.filter(jadwalpelajaran=nama_matkul)  
    data.delete()  
    return redirect("/jadwalmu")  

def edit(request, id):  
    data = Jadwal.objects.get(id=id)  
    return render(request,'schedule/edit.html', {'data': data})  


def update(request, id):  
    data = Jadwal.objects.get(id=id)  
    form = JadwalForms(request.POST, instance = data)  
    if form.is_valid():  
        form.save()  
        return redirect("/jadwalmu")  
    else:
        #form.save()
        return redirect("/jadwalmu")
    return render(request, 'schedule/edit.html', {'data': data})  

schedule/templates/schedule/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Schedule</title>
    <link rel="stylesheet" href="../../static/schedule/style.css" type="text/css" media="screen">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" 
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" 
    crossorigin="anonymous">
</head>

<body>
    <div class="sidenav">
        <div class="halo">
            <h1 style="font-size: 18px;">Halo</h1>
        </div>
        <a href="{% url 'homepage:index' %}">Home</a>
        <a href="{% url 'schedule:index' %}">Jadwal</a>
        <a href="{% url 'todo:index' %}">To Do List</a>
        <a href="{% url 'nilai:index' %}">Nilai</a>
        <a href="{% url 'notes:index' %}">Notes</a>
        <button type="button" class="btn btn-outline-dark">Log out</button>
    </div>
    {% block content %}
    {% endblock %}

</body>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</html>

schedule/templates/schedule/edit.html
{% extends 'schedule/base.html' %}
{% load static %}

{% block content %}


<body>  
  <div class="center_div offset-md-4">
    <form method="POST" class="post-form" action="/jadwalmu/update/{{ data.id }}" >  
            {% csrf_token %}  
        <div class="container">  
    <br>  
        <div class="form-group row">  
        <label class="col-sm-1 col-form-label"></label>  
        <div class="col-sm-4">  
        <h3>Ubah Jadwal-Pelajaran</h3>  
        </div>  
      </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Schedule Name:</label>  
        <div class="col-sm-4">  
            <input type="text" name="jadwalpelajaran" required maxlength="20" value="{{ data.jadwalpelajaran}}"/>  
        </div>  
      </div>  
      <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Deskripsi:</label>  
        <div class="col-sm-4">  
            <input type="text" name="deskripsi"  required maxlength="300" value="{{ data.deskripsi }}" />  
        </div>  
      </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Tanggal:</label>  
        <div class="col-sm-4">  
            <input type="date" name="datetime"  required maxlength="254" value="{{ data.datetime }}" />  
        </div>  
      </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Lokasi:</label>  
        <div class="col-sm-4">  
            <input type="text" name="lokasi" required maxlength="15" value="{{ data.lokasi }}" />  
        </div>  
      </div>  
        <div class="form-group row">  
        <label class="col-sm-1 col-form-label"></label>  
        <div class="col-sm-4">  
        <a href="/jadwalmu">
          <button type="submit" class="btn btn-success" id="buto">Update</button> 
        </a> 
        </div>  
      </div>  
        </div>  
    </form>  
  </div>

  <div class="bekgron">
  </div>
  
    </body>  

{% endblock %}

schedule/templates/schedule/listJadwal.html
{% extends 'schedule/base.html' %}
{% load static %}

{% block content %}
<body>

    {% for i in data %}
    <div class="center_div offset-md-4"> 
            <table style="border:3px solid rgb(172, 59, 224);" class="table table-bordered">
                <tbody>
                <tr>
                    <th scope="row">Nama Pelajaran</th>
                    <td>{{ i.jadwalpelajaran }}</td>
                </tr>
                <tr>
                    <th scope="row">Deskripsi</th>
                    <td>{{ i.deskripsi }}</td>
                </tr>
                <tr>
                    <th scope="row">Tanggal</th>
                    <td>{{ i.datetime }}</td>
                </tr>
                <tr>
                    <th scope="row">Lokasi</th>
                    <td>{{ i.lokasi }}</td>
                </tr>

                </tbody>
            </table>
        </div>
        <br><br>
        <div class="center_div offset-md-4"> 
            <a href="/jadwalmu">
                <button type="submit" class="btn btn-success" id="buto">Back</button>
            </a>
            <a href="/jadwalmu/delete/{{ i.jadwalpelajaran }}">
                <button type="submit" class="btn btn-success" id="buto">Delete</button>
            </a>
            <a href="/jadwalmu/edit/{{ i.id }}">
                <button type="submit" class="btn btn-success" id="buto">Edit</button>
            </a>  
            <br>
        </div>
    {% endfor %}
    

</body>
{% endblock %}

schedule/templates/schedule/schedule.html
{% extends 'schedule/base.html' %}
{% load static %}

{% block content %}

<body>
    <div class="container center_div offset-md-4"> 
        <form method="POST" class="post-form" action="">  
            {% csrf_token %}  
        <div class="container">  
    <br>  
        <div class="form-group row">  
        <label class="col-sm-1 col-form-label"></label>  
        <div class="col-sm-4">  
        <h3>Masukkan Jadwal-Pelajaran Kamu!</h3>  
        </div>  
    </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Schedule Name:</label>  
        <div class="col-sm-4">  
        {{ form.jadwalpelajaran }}  
        </div>  
    </div>  
    <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Deskripsi:</label>  
        <div class="col-sm-4">  
        {{ form.deskripsi }}  
        </div>  
    </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label" data-target-input="nearest" >Tanggal:</label>  
        <div class="col-sm-4">  
        {{ form.datetime }}  
        
        </div>  
    </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Lokasi:</label>  
        <div class="col-sm-4">  
        {{ form.lokasi }}  
        </div>  
    </div>  
        <div class="form-group row">  
        <label class="col-sm-1 col-form-label"></label>  
        <div class="col-sm-4">  
        <button type="submit" class="btn btn-primary" id="buto">Submit</button>  
        </div>  
    </div>  
        </div>  
    </form> 
    </div> 


        <div id="tabil" class="container"> 
        <table style="margin-left:auto;margin-right:auto;">
            <tr>
                <th>Jadwal</th>
            </tr>
            {% for i in data %}
                <tr>
                    <td>
                        <a href="/jadwalmu/{{ i.jadwalpelajaran }}">
                            <p>{{ i.jadwalpelajaran }}</p>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </table>

        
    </div>
       

<div class="bekgron">
</div>

    </body>
  
    {% endblock %}
    </html>